name: Build embeddings

on:
  push:
    branches: [ main ]
    paths:
      - "knowledge/**"
      - "scripts/build_embeddings.js"
      - "package.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Build embeddings
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run embed

      # Publiceer ook naar GitHub Pages (docs/)
      - name: Copy embed to docs
        run: cp embeddings.json docs/embeddings.json

      - name: Commit embeddings.json
        run: |
          git add embeddings.json docs/embeddings.json
          git commit -m "chore: update embeddings" || echo "no changes"
          git push
